### ISSUE TITLE
Big bug found

### ISSUE THREAD

**Issue by Kopamed** [federicadomani/AutoClicker2-Record-Play-The-Lists-Of-Mouse-Clicks#11]
Your bots spam users with an email along the lines of 
"
Hi!

I found your email at GitHub. I am a GitHub user too.
My daughter is an amateur programmer in GitHub.
She is an author of the open source project
AutoClicker2 Record Play The Lists Of Mouse Clicks:

https://github.com/federicadomani/AutoClicker2-Record-Play-The-Lists-Of-Mouse-Clicks

Just add a GitHub star if you support this open source project!
"

Just thought you might wanna fix this bug. Also, never knew that GitHub is a programming language

**Comment by federicadomani** [comment]
It was not a bot. It is my ex-boyfriend. Thank you for notification. Fixed.

**Comment by he3als** [comment]
This project is a cryptocurrency miner (malware). It installs an 'update service' in the background by default without telling you, and it uses very high CPU usage and memory usage. It is actually a miner, and here's where the encrypted zip (disguised as .dat files) are in the UPD folder in: https://github.com/federicadomani/AutoClicker2-Record-Play-The-Lists-Of-Mouse-Clicks/tree/master/Installer

There's another account (probably owned by the same person) with an autoclicker very similar, and it is also malware.

https://github.com/windows-2048/The-Fastest-Mouse-Clicker-for-Windows/tree/master/InnoSetupDownloader

@Kopamed they're doing that so they can get more computers infected with miners lol
