### ISSUE TITLE
MALWARE. DO NOT DOWNLOAD

### ISSUE THREAD

**Issue by jferris-** [federicadomani/AutoClicker2-Record-Play-The-Lists-Of-Mouse-Clicks#15]
https://www.hybrid-analysis.com/sample/2c28f9dfe58a0cc72d76974220ede5b8686f97bfd8a699edc57748fc9459c20b

**Comment by federicadomani** [comment]
This is long known false positive:
https://www.virustotal.com/gui/file/5222d626ba0444154b28822aced3272a8130a8e389d52cb1133d55715e1d1807/community
