### ISSUE TITLE
AutoClicker2 does not show current mouse position

### ISSUE THREAD

**Issue by BigBadWorld-art** [federicadomani/AutoClicker2-Record-Play-The-Lists-Of-Mouse-Clicks#2]
AutoClicker2 does not show current mouse position, while AutoClicker2Ex does.
I need to see that position when I select a point to click on in fixed mode clicking.

**Comment by federicadomani** [comment]
Hmm. You are right. I will add this feature into AutoClicker2 next release.

**Comment by sersneval34** [comment]
AutoClicker2 v5.9.3.1 does how mouse position in both programs
