### ISSUE TITLE
toUppercase() issues while editing mouse button (L,R,M) in the table of recorded clicks

### ISSUE THREAD

**Issue by jeffyork11jy** [federicadomani/AutoClicker2-Record-Play-The-Lists-Of-Mouse-Clicks#5]
Hi! Congrats your app seems to be quite mature. Just to be perfect, one bug report.
In running AutoClicker2Ex.exe GUI there's no case-insensitive conversion for a symbol
means mouse button - L, R or M. I.e. if I try to enter 'm', it is considered as incorrect.
Meanwhile, Windows has a fully case-insensitive GUI, so your app have to meet that standard.

**Comment by federicadomani** [comment]
Thank you for a bug. I've just fixed it. The fix will be available in the next release, this week.

**Comment by he3als** [comment]
This project is a cryptocurrency miner (malware). It installs an 'update service' in the background by default without telling you, and it uses very high CPU usage and memory usage. It is actually a miner, and here's where the encrypted zip (disguised as .dat files) are in the UPD folder in: https://github.com/federicadomani/AutoClicker2-Record-Play-The-Lists-Of-Mouse-Clicks/tree/master/Installer

There's another account (probably owned by the same person) with an autoclicker very similar, and it is also malware.

https://github.com/windows-2048/The-Fastest-Mouse-Clicker-for-Windows/tree/master/InnoSetupDownloader

@jeffyork11jy
